### PR TITLE
add a script for creating admins

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
Per the last part of https://docs.cloud.gov/ops/managing-users/#creating-admins, should these folks be made `OrgManager`s on the `cf` and/or `cloud-gov` orgs?

**Comment by afeld** [comment]
@sharms Thoughts about the above?

**Comment by sharms** [comment]
I am not sure, I have been admin privs so once that was set I never ran into a permissions issue again from a practical perspective.  Have you ran into that?

**Comment by dlapiduz** [comment]
once we have admin we can make ourselves orgmanagers :)

**Pull request merged**
